### ISSUE TITLE
https://unite.eu/developers/errors/invalid does not exist anymore

### ISSUE THREAD

**Issue by Mortinke** [Mercateo/rest-jersey-utils#13]
The type/URL `https://unite.eu/developers/errors/invalid` used in [ConstraintViolationExceptionMapper](https://github.com/Mercateo/rest-jersey-utils/blob/d293c6e76c0c928ef8e799b35be9c8e3c705e119/src/main/java/com/mercateo/rest/jersey/utils/exception/ConstraintViolationExceptionMapper.java#L40) does not exist. We should update this to current valid URL `https://portal.unite.eu/de_DE/developers/errors/invalid`.

Based on the comment of @mweirauch [here](https://github.com/Mercateo/rest-jersey-utils/pull/12#discussion_r244869502), this URL may need to be configurable.

**Comment by JoergAdler** [comment]
Right one is http://developers.unite.eu/errors/invalid

**Comment by Mortinke** [comment]
fixed in #14
