### ISSUE TITLE
CustomErrorResponse for JsonMappingExceptions

### ISSUE THREAD

**Issue by OOlsen** [Mercateo/rest-jersey-utils#18]
When the JsonReader encounters InvalidArgumentExceptions  during deserialization (before the ValiationApi can step in) a JsonMappingExceptions is thrown. This exception should be mapped in a readable error response. The library jersey-media-json-jackson already provides a org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.JsonMappingExceptionMapper, but with quite few information.

**Comment by OOlsen** [comment]
I will provide a PR for this topic.

**Comment by Mortinke** [comment]
fixed with #19
